#!/usr/bin/env bash
# =============================================================================
# LMP Vrinda Finance Engine — one-shot VPS deployment.
#
# Copy the whole project to your VPS, then run:   ./deploy.sh
#
# On first run it installs Docker (if missing), asks a few questions, writes a
# server .env with generated secrets, builds, and starts the app behind Caddy
# with automatic HTTPS. Re-running it later safely updates the app.
#
# Tested target: a fresh Ubuntu/Debian VPS with sudo. Run as root or a sudo user.
# =============================================================================
set -euo pipefail

cd "$(dirname "$0")"

ENV_FILE="./.env.deploy"
COMPOSE_FILE="deploy/docker-compose.prod.yml"

say()  { printf "\n\033[1;34m==>\033[0m %s\n" "$*"; }
ok()   { printf "\033[1;32m  ✓\033[0m %s\n" "$*"; }
warn() { printf "\033[1;33m  !\033[0m %s\n" "$*"; }
die()  { printf "\n\033[1;31mERROR:\033[0m %s\n" "$*" >&2; exit 1; }

# --- 0. sudo helper (works whether or not we are already root) ----------------
SUDO=""
if [ "$(id -u)" -ne 0 ]; then
  command -v sudo >/dev/null 2>&1 || die "Please run as root or install sudo."
  SUDO="sudo"
fi

# --- 1. Install Docker + compose plugin if missing ----------------------------
install_docker() {
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    ok "Docker and Compose already installed."
    return
  fi
  say "Installing Docker (this can take a minute)…"
  $SUDO apt-get update -y
  $SUDO apt-get install -y ca-certificates curl gnupg
  $SUDO install -m 0755 -d /etc/apt/keyrings
  if [ ! -f /etc/apt/keyrings/docker.gpg ]; then
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
      | $SUDO gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    $SUDO chmod a+r /etc/apt/keyrings/docker.gpg
  fi
  . /etc/os-release
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/${ID} ${VERSION_CODENAME} stable" \
    | $SUDO tee /etc/apt/sources.list.d/docker.list >/dev/null
  $SUDO apt-get update -y
  $SUDO apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  $SUDO systemctl enable --now docker
  ok "Docker installed."
}

# --- 2. First-run configuration (writes .env.deploy) --------------------------
rand_secret() { openssl rand -base64 48 | tr -d '\n/+=' | cut -c1-48; }

hash_password() {
  # bcrypt hash via a one-off python:3.12 container (no local python needed).
  local plain="$1"
  docker run --rm python:3.12-slim sh -c \
    "pip install --quiet bcrypt >/dev/null 2>&1; python -c \"import bcrypt,sys; print(bcrypt.hashpw(sys.argv[1].encode(),bcrypt.gensalt()).decode())\" '$plain'"
}

configure() {
  if [ -f "$ENV_FILE" ]; then
    ok "Using existing $ENV_FILE (delete it to reconfigure)."
    return
  fi
  say "First-time setup — a few questions:"

  read -rp "  Environment [production/development] (production): " APP_ENV
  APP_ENV="${APP_ENV:-production}"
  case "$APP_ENV" in
    prod|production) APP_ENV="production" ;;
    dev|development) APP_ENV="development" ;;
    *) warn "Unrecognized env '$APP_ENV' — defaulting to production."; APP_ENV="production" ;;
  esac

  read -rp "  Domain for HTTPS (blank = serve on server IP over HTTP): " DOMAIN
  if [ -n "$DOMAIN" ]; then
    SITE_ADDRESS="$DOMAIN"
    FRONTEND_ORIGIN="https://$DOMAIN"
  else
    SITE_ADDRESS=":80"
    FRONTEND_ORIGIN="*"
    warn "No domain given — serving plain HTTP on the IP. Add a domain later for HTTPS."
  fi

  read -rp "  Admin username [admin]: " AUTH_USERNAME
  AUTH_USERNAME="${AUTH_USERNAME:-admin}"

  local p1 p2
  while :; do
    read -rsp "  Admin password (min 8 chars): " p1; echo
    read -rsp "  Confirm password: " p2; echo
    [ "$p1" = "$p2" ] || { warn "Passwords do not match."; continue; }
    [ "${#p1}" -ge 8 ] || { warn "Too short."; continue; }
    break
  done

  if [ "$APP_ENV" = "production" ]; then
    # Production is locked to the hosted provider; others are refused by the API.
    EXTRACTION_PROVIDER="openrouter"
    ok "Production: extraction provider forced to 'openrouter' (others are blocked)."
  else
    read -rp "  Extraction provider [openrouter/ollama/tesseract/stub] (openrouter): " EXTRACTION_PROVIDER
    EXTRACTION_PROVIDER="${EXTRACTION_PROVIDER:-openrouter}"
  fi
  OPENROUTER_API_KEY=""
  if [ "$EXTRACTION_PROVIDER" = "openrouter" ]; then
    read -rp "  OpenRouter API key: " OPENROUTER_API_KEY
  fi

  say "Generating secrets and hashing password…"
  local JWT_SECRET PW_HASH PW_HASH_ESC
  JWT_SECRET="$(rand_secret)"
  PW_HASH="$(hash_password "$p1")"
  [ -n "$PW_HASH" ] || die "Password hashing failed (is Docker working?)."

  # Docker Compose --env-file does $-interpolation. bcrypt hashes contain '$'
  # (e.g. $2b$12$...), so escape each '$' as '$$' to keep the hash literal.
  PW_HASH_ESC="${PW_HASH//\$/\$\$}"

  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Keep this file secret.
APP_ENV=$APP_ENV
SITE_ADDRESS=$SITE_ADDRESS
FRONTEND_ORIGIN=$FRONTEND_ORIGIN
AUTH_USERNAME=$AUTH_USERNAME
AUTH_PASSWORD_HASH=$PW_HASH_ESC
JWT_SECRET=$JWT_SECRET
JWT_EXPIRY_HOURS=3
EXTRACTION_PROVIDER=$EXTRACTION_PROVIDER
OPENROUTER_API_KEY=$OPENROUTER_API_KEY
EOF
  ok "Wrote $ENV_FILE (permissions 600)."
}

# --- 3. Build and start -------------------------------------------------------
launch() {
  say "Building and starting containers…"
  $SUDO docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d --build
  ok "Containers started."
  say "Status:"
  $SUDO docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" ps
}

# --- main ---------------------------------------------------------------------
install_docker
configure
launch

# Read only the two display values WITHOUT sourcing the file — a bcrypt hash
# contains '$' sequences that bash would try (and fail) to expand under set -u.
SITE_ADDRESS="$(sed -n 's/^SITE_ADDRESS=//p' "$ENV_FILE")"
AUTH_USERNAME="$(sed -n 's/^AUTH_USERNAME=//p' "$ENV_FILE")"
say "Done."
if [ "$SITE_ADDRESS" = ":80" ]; then
  echo "  Open:  http://<your-server-ip>/"
else
  echo "  Open:  https://$SITE_ADDRESS/   (HTTPS provisions automatically on first visit)"
fi
echo "  Login: $AUTH_USERNAME / (the password you set)"
echo
echo "  Update later:   git pull && ./deploy.sh"
echo "  View logs:      docker compose --env-file $ENV_FILE -f $COMPOSE_FILE logs -f"
echo "  Stop:           docker compose --env-file $ENV_FILE -f $COMPOSE_FILE down"
